/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package bonko

import kotlinx.coroutines.runBlocking
import java.io.File

fun main() {
    println("Setting up Bun...")
    val path = runBlocking { setupBun("./downloaded", "0.5.9") }
    val sampleCode = """const a: string = "10";"""
    val bun = Bun(path)

    println("Transpiling Typescript code String: '$sampleCode")
    val (result, errs) = bun.transpile("ts", sampleCode)
    println(result)
    System.err.println(errs)

    val tsxFile = File("./test.jsx")
    println("Transpiling JSX FSile: ${tsxFile.path}")

    val (fileResult, fileErrs) = bun.transpile(tsxFile)

    println(fileResult)
    System.err.println(fileErrs)

    val server = createServer(bun)
    server.start(wait=true)
}
